### ISSUE TITLE
Missing some C types in WIDTH_TYPES

### ISSUE THREAD

**Issue by markoshorro** [zwegner/x86-sat#2]
[WIDTH_TYPES](https://github.com/zwegner/x86-sat/blob/5ad1ee5d65a0e5ba3236ee583986c81800caaa98/x86_sat/evaluate.py#L91) is missing other types such as `__m128`, `__m128d`, `__m512`, `__m512d`. I have no idea if this is intentional or a limitation of the current model implemented.

**Comment by zwegner** [comment]
No reason really, I guess I just hadn't used any intrinsics with those types yet. Fixed.

**Comment by markoshorro** [comment]
Thanks! It is also needed other types missing such as `float` and `double`.

**Comment by zwegner** [comment]
That is intentional actually, since float types aren't yet supported. I'd like to add support someday, but it'll be tricky to get all the details right...

**Comment by markoshorro** [comment]
I am having issues understanding why that could happen, shouldn't `float` cases behave the same as 32-bit `int` cases (which are already considered in your code)? Thanks for your comments.

EDIT:
I am sorry to be such a pain but, I have included `float` as a 32-bit type and I am able to use `XXX_ps` instructions without errors.

**Comment by zwegner** [comment]
Floats need a separate implementation: all the operations translate to very different SAT equations, and it's a different type that needs to be tracked in a lot of places. This isn't super hard, since values already track the bit width and signedness of integers, and z3 does have float types, but there are a lot of details that could go wrong. The Intel pseudocode uses all the same operations for floats/ints, so `a + b` or `MAX(a, b)` is a completely different operation based on the types of a and b. We'd have to add support for different rounding modes, and make sure cases like fused multiply-add don't have an intermediate rounding step between the multiply and add (which requires some hacks since in the pseudocode it's just `a * b + c`).

If the float operations worked for you, it must just be a coincidence (are the values integers?), because x86-sat doesn't use any floating point equations yet. Also, you're not being a pain--I'm glad people are finding x86-sat useful!
